#!/usr/bin/env bash
# 100-advanced


echo "$$" > /var/run/myscript.pid

cleanup() {
	rm /var/run/myscript.pid
	exit
}


while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && cleanup' SIGTERM
	trap 'cleanup' SIGQUIT
done
